groups:
- name: postgres_base.rules
  rules:
  # ───────────────────────────────────────────────
  # DISPONIBILIDADE
  # ───────────────────────────────────────────────
  - alert: PostgresDown
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL offline em {{ $labels.instance }}"
      description: |
        A instância {{ $labels.instance }} não responde ao exporter
        há pelo menos 1 minuto.

  # ───────────────────────────────────────────────
  # CONEXÕES
  # ───────────────────────────────────────────────
  - alert: ConnectionsHigh
    expr: |
      100 *
      (sum by (instance)(pg_stat_database_numbackends))
        /
      (sum by (instance)(pg_settings_max_connections))
      > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Uso de conexões > 80 % em {{ $labels.instance }}"
      description: |
        O total de conexões ativas passou de 80 % da
        configuração max_connections.

  # ───────────────────────────────────────────────
  # TAXA DE TRANSAÇÕES
  # ───────────────────────────────────────────────
  - alert: NoTransactions
    expr: |
      rate(pg_stat_database_xact_commit[5m]) +
      rate(pg_stat_database_xact_rollback[5m]) < 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Sem transações nos últimos 5 min em {{ $labels.instance }}"
      description: |
        Nenhuma transação foi registrada na instância,
        o que pode indicar indisponibilidade de aplicação.

  # ───────────────────────────────────────────────
  # LATÊNCIA MÉDIA (pg_stat_statements)
  # ───────────────────────────────────────────────
  - alert: QueryLatencyHigh
    expr: |
      increase(pg_stat_statements_total_time[5m])
        /
      increase(pg_stat_statements_calls[5m])
      > 0.5
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "Latência média > 500 ms em {{ $labels.instance }}"
      description: |
        A média de duração das queries excedeu 500 ms
        na janela de 5 minutos.

  # ───────────────────────────────────────────────
  # CACHE HIT RATIO
  # ───────────────────────────────────────────────
  - alert: CacheHitRatioLow
    expr: |
      (rate(pg_stat_database_blks_hit[5m]))
        /
      (rate(pg_stat_database_blks_hit[5m]) + rate(pg_stat_database_blks_read[5m]))
      < 0.99
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Cache hit ratio < 99 % em {{ $labels.instance }}"
      description: |
        Baixa taxa de acerto no cache indica pressão de I/O.

  # ───────────────────────────────────────────────
  # I/O DE DISCO (leituras de bloco)
  # ───────────────────────────────────────────────
  - alert: DiskReadsHigh
    expr: |
      rate(pg_stat_database_blks_read[1m]) * 8 * 1024 > 10485760   # > 10 MB/s
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Leitura de disco > 10 MB/s em {{ $labels.instance }}"
      description: |
        A taxa de leitura superou 10 MB por segundo
        na última janela de 1 minuto.

  # ───────────────────────────────────────────────
  # CHECKPOINTS EXCESSIVOS
  # ───────────────────────────────────────────────
  - alert: FrequentCheckpoints
    expr: |
      rate(pg_stat_bgwriter_checkpoints_timed[5m]) > 0.1   # > 1 a cada 10 min
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Checkpoints frequentes em {{ $labels.instance }}"
      description: |
        Mais de 6 checkpoints por hora — pode indicar
        configuração subótima de checkpoint_timeout/WAL.

  # ───────────────────────────────────────────────
  # AUTOVACUUM NÃO RODA HÁ MUITO TEMPO
  # ───────────────────────────────────────────────
  - alert: AutovacuumStale
    expr: |
      time() - pg_stat_user_tables_last_autovacuum > 86400  # > 24 h
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "Autovacuum atrasado em {{ $labels.relname }}"
      description: |
        A tabela {{ $labels.relname }} não recebe autovacuum
        há mais de 24 horas.

  # ───────────────────────────────────────────────
  # DEADLOCKS
  # ───────────────────────────────────────────────
  - alert: DeadlocksDetected
    expr: increase(pg_stat_database_deadlocks[5m]) > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Deadlock detectado em {{ $labels.instance }}"
      description: |
        Um ou mais deadlocks ocorreram nos últimos 5 minutos.

  # ───────────────────────────────────────────────
  # BLOAT > 20 %  (métrica via query custom pg_table_bloat_ratio)
  # ───────────────────────────────────────────────
  - alert: TableBloatHigh
    expr: pg_table_bloat_ratio > 20
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Bloat > 20 % na tabela {{ $labels.relname }}"
      description: |
        A tabela {{ $labels.relname }} apresenta bloat estimado
        acima de 20 %. Considere re-indexar ou CLUSTER.

  # ───────────────────────────────────────────────
  # LAG DE REPLICAÇÃO (hot standby)
  # ───────────────────────────────────────────────
  - alert: ReplicationLagHigh
    expr: pg_replication_lag_bytes > 104857600   # > 100 MB
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Lag de replicação > 100 MB em {{ $labels.instance }}"
      description: |
        O atraso de replicação ultrapassou 100 MB por 5 minutos.
